# -*- coding: utf-8 -*-
"""
/***************************************************************************
selecionaysiguiente
                                 A QGIS plugin
 Permite crear una capa de poligonos partiendo de los elementos de una capa de puntos. Si se seleccionan ciertos elemento solo se tendran estos en cuenta.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-29
        copyright            : (C) 2019 by javier diez
        email                : dierabfr@jcyl.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Puntos Sigmena class from file ptos2pol.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .selecionaysiguiente import selecionaysiguiente
    return selecionaysiguiente(iface)
