# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OruxmapsSigmena
                                 A QGIS plugin
 Crea mapas para oruxmaps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-18
        copyright            : (C) 2018 by Klas Karlsson
        email                : klaskarlsson@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayoutLoader class from file LayoutLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .oruxmaps_sigmena import OruxmapsSigmena
    return OruxmapsSigmena(iface)
